name: Create Release

on:
  push:
    branches:
      - main # Adjust based on your branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            Release notes for ${{ env.VERSION }}.
            - updated.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
